// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxF4Hk5XJ2XzP19yT-WHNhGjDi425a9zk',
    appId: '1:977675162441:web:088818b06e2bad086f0098',
    messagingSenderId: '977675162441',
    projectId: 'hr-self-service-edd1e',
    authDomain: 'hr-self-service-edd1e.firebaseapp.com',
    storageBucket: 'hr-self-service-edd1e.firebasestorage.app',
    measurementId: 'G-DS8P67V23J',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBibd4TnItrNEqhu4g_GysjLKcquQU5MGQ',
    appId: '1:977675162441:ios:8d08bb09c2ccc8d66f0098',
    messagingSenderId: '977675162441',
    projectId: 'hr-self-service-edd1e',
    storageBucket: 'hr-self-service-edd1e.firebasestorage.app',
    iosBundleId: 'com.example.hrSelfService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBibd4TnItrNEqhu4g_GysjLKcquQU5MGQ',
    appId: '1:977675162441:ios:8d08bb09c2ccc8d66f0098',
    messagingSenderId: '977675162441',
    projectId: 'hr-self-service-edd1e',
    storageBucket: 'hr-self-service-edd1e.firebasestorage.app',
    iosBundleId: 'com.example.hrSelfService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxF4Hk5XJ2XzP19yT-WHNhGjDi425a9zk',
    appId: '1:977675162441:web:d28f95df1cbf51456f0098',
    messagingSenderId: '977675162441',
    projectId: 'hr-self-service-edd1e',
    authDomain: 'hr-self-service-edd1e.firebaseapp.com',
    storageBucket: 'hr-self-service-edd1e.firebasestorage.app',
    measurementId: 'G-3NTEHGJSR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDxk6_0uexBPwHL009mZQ3GtN9PLMbM1w',
    appId: '1:977675162441:android:1b81755f584b6ff86f0098',
    messagingSenderId: '977675162441',
    projectId: 'hr-self-service-edd1e',
    storageBucket: 'hr-self-service-edd1e.firebasestorage.app',
  );

}